services: 
  nginx: 
    container_name: nginx
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile      
    ports:
      - "81:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
      - redis
      - php

  mysql: 
    image: mysql:8.0
    restart: unless-stopped
    tty: true
    ports: 
      - "3307:3306"
    environment:
      MYSQL_DATABASE: fms
      MYSQL_USER: detpos
      MYSQL_PASSWORD: asdffdsa
      MYSQL_ROOT_PASSWORD: asdffdsa 
    volumes:
      - ./dockerfiles/mysql:/var/lib/mysql

  php: 
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"

  redis: 
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6380:6379"

  mosquitto:
    build: 
      context: ./dockerfiles
      dockerfile: mosquitto.dockerfile
    ports:
      - "1884:1883"
      - "9002:9001"
    volumes:
      - ./dockerfiles/mosquitto/mosquitto.conf:/etc/mosquitto/mosquitto.conf
      - ./dockerfiles/mosquitto/passwd:/etc/mosquitto/passwd
    restart: unless-stopped

  composer: 
    build: 
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html

  npm: 
    image: node:current-alpine
    volumes: 
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    
  artisan: 
    build: 
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes: 
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    entrypoint: ['php', '/var/www/html/artisan']

  supervisor:
    build:
      context: ./dockerfiles
      dockerfile: supervisor.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    